---  # Resolve Proxy Encoder User configuration file

# NOTE: 
# Proxy paths, codecs, resolution, filters, etc are all inherited from the queuer's user configuration.
# 'Celery' and 'Worker' settings are pulled from local user configuration.
app:

  loglevel: WARNING
  check_for_updates: true
  update_check_url: "https://github.com/in03/resolve-proxy-encoder"  # Change this url if you fork
  disable_version_constrain: false # DANGEROUS! Allows any version of worker to take jobs. Must be set on queuer and worker. 

paths:

  proxies_with_source_media: true # Use with Resolve 18's automatic linking feature. Overrides proxy_path_root. 
  proxies_in_one_folder: /volumes/Resolve/ProxyMedia # Keep proxies on a single drive, retain structure, manually link.
  
  path_maps: 

  # Proxy media location
   - win: R:/ # UNC paths with hostname recommended
     mac: /volumes/Resolve 
     linux: /mnt/Resolve

   # Active projects location
   - win: Z:/
     mac: /volumes/YouTourActive
     linux: /mnt/YouTourActive
  
  # Archived projects location
   - win: A:/
     mac: /volumes/YouTourArchive
     linux: /mnt/YouTourArchive

  ### Add additional path maps as needed! ###
  #  - win: M:/
  #    mac: /volumes/MySpecialPath
  #    Linux: /mnt/MySpecialPath


proxy: # Use ProRes for Mac M1 machines

  ffmpeg_loglevel: error # # Standard ffmpeg loglevels
  codec: dnxhd
  vertical_res: "720"
  profile: dnxhr_sq
  pix_fmt: yuv422p
  audio_codec: pcm_s16le
  audio_samplerate: "48000"
  misc_args: [-hide_banner, -stats]
  ext: .mov

filters:

  # Remove elements from lists to disable filter
  extension_whitelist : [.mov, .mp4, .mxf, .avi] 
  framerate_whitelist : [24, 25, 30, 50, 60]

celery:

  host_address: 192.168.1.19
  broker_url:  redis://192.168.1.19:6379/0
  flower_url: http://192.168.1.19:5555
  result_backend: redis://192.168.1.19:6379/0
  result_expires: 60 # 10 mins

worker:

  loglevel: INFO
  concurrency: 1
  prefetch_multiplier: 1
  max_tasks_per_child: 1
  terminal_args: [] # use alternate shell? Recommend windows terminal ("wt") on Windows.
  celery_args: [-l, INFO, -P, solo, --without-mingle, --without-gossip]
