fail_fast: false
repos:

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
     - id: check-toml
     - id: pretty-format-json
     - id: check-vcs-permalinks
     - id: detect-private-key

ci:

  autofix_commit_msg: "chore: [pre-commit.ci] automatic fixes"
  autoupdate_commit_msg: "chore: [pre-commit.ci] automatic update"
